<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="PartsBlazor.Tests\**\*.cs" />
        <Content Remove="PartsBlazor.Tests\**" />
        <None Remove="PartsBlazor.Tests\**" />
    </ItemGroup>

    <Target Name="CompileTypeScript" BeforeTargets="Build">
        <Exec Command="npm install" Condition="!Exists('node_modules')" WorkingDirectory="$(MSBuildProjectDirectory)" />
        <Exec Command="npm run build" WorkingDirectory="$(MSBuildProjectDirectory)" />
    </Target>

</Project>
